### ISSUE TITLE
Is it possible to control 'strength' of denoising?

### ISSUE THREAD

**Issue by filibis** [troopy28/OptiX-Denoiser-for-Blender#2]
Hi Maxime,

Is it possible to control 'strength' of denoising (similar to built in features that Blender denoising has)?
Right now it soften outs the render dramatically that I lose most material and edge details. I create interior renders with above 500 samples which generates a few noise.

I use Blender 2.79.5

Thanks,

Emir

**Comment by troopy28** [comment]
Hello there,

Sadly, the addon doesn't provide any control over the denoising quality. This is because it is only a bridge to an existing denoiser, which does not have a lot of possibilities of customization. See here to customize it a bit: https://github.com/DeclanRussell/NvidiaAIDenoiser

**But**, I'm working on a version of this addon which does not depend on an external excutable. This one will have customization capabilities, and I hope better performance since it will be directly embedded into the addon (I won't be calling another software to do the job).
EDIT: not anymore, since the D-Noiser addon (which by the way is, at the moment I write this, _exactly_ the same thing with a better publicity) is widely adopted, and Blender 2.81 embeds the Intel AI denoiser.
